import {StyleSheet} from 'react-native';

export const Styles = StyleSheet.create({
  main: {
    backgroundColor: '#1A1A1A',
    flex: 1,
  },
  addTaskContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: -27,
  },
  img: {width: 16, height: 16},
  containerInfo: {
    alignItems: 'center',
    marginBottom: 20,
  },
  wrapperInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 327,
    marginTop: 32,
  },
  containerEmpty: {
    alignItems: 'center',
    marginTop: 20,
  },
  containerTask: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    backgroundColor: '#0D0D0D',
    height: 173,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    padding: 16,
    backgroundColor: '#262626',
    border: '1px solid #0D0D0D',
    color: '#F2F2F2',
    lineHeight: 22.4,
    fontWeight: '400',
    fontSize: 16,
    borderRadius: 6,
    width: 271,
    height: 54,
    fontFamily: 'Inter',
  },
  button: {
    backgroundColor: '#1E6F9F',
    padding: 18,
    borderRadius: 6,
    width: 54,
    height: 54,
    marginLeft: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addTaskButtonContainerIcon: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    // width: 20,
    // height: 20,
  },
  addTaskButtonIcon: {position: 'absolute', zIndex: 99, border: 'none'},
  wrapperStatus: {flexDirection: 'row'},
  info: {fontFamily: 'Inter', fontWeight: '700', fontSize: 14, lineHeight: 17},
  created: {
    color: '#4EA8DE',
    marginRight: 8,
  },
  completed: {color: '#8284FA', marginRight: 8},
  counter: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: '#333333',
    borderRadius: 999,
    color: '#D9D9D9',
    fontSize: 12,
    fontWeight: '700',
    fontFamily: 'Inter',
    lineHeight: 15,
  },
  empty: {
    borderTopColor: '#333333',
    borderTopWidth: 1,
    width: 327,
    height: 208,
    alignItems: 'center',
  },
  emptyText: {
    fontFamily: 'Inter',
    fontSize: 14,
    color: '#808080',
    lineHeight: 19.6,
  },
  emptyTitle: {fontWeight: '700', marginTop: 16},
  emptySubTitle: {fontWeight: '400'},
  clipboard: {width: 56, height: 56, marginTop: 48},
  taskWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 327,
    backgroundColor: '#262626',
    paddingTop: 12,
    paddingRight: 8,
    paddingLeft: 12,
    paddingBottom: 12,
    marginTop: 8,
    shadowColor: 'rgba(0, 0, 0, 0.06)',
    borderRadius: 8,
  },
  taskCheckBox: {},
  textbox: {
    width: 180,
    flexDirection: 'row',
    flex: 1,
  },
  taskText: {
    color: '#F2F2F2',
    marginLeft: 8,
    marginRight: 18,
    fontFamily: 'Inter',
    fontSize: 14,
    lineHeight: 19.6,
    fontWeight: '400',
  },
  taskCompletedText: {textDecorationLine: 'line-through', color: '#808080'},
  taskSound: {width: 30},
  taskButton: {marginRight: 10},
  taskIcon: {},
});
